### ISSUE TITLE
When I type `npx create-boring-app my-app` into my terminal, nothing happens.

### ISSUE THREAD

**Issue by josheverett** [ryanstevens/boringbits#11]
Expected result: A fully scaffolded hello world app with love and/or hot reload.

Actual result: Sadness and heartache.

**Comment by ryanstevens** [comment]
Sad panda.  Agree this should work

**Comment by ryanstevens** [comment]
Question.  Can this be doing after you install Boring, so it works via npx inside am empty repo or should this be a stand alone cli.  I greatly prefer the npx route at least for first steps

**Comment by ryanstevens** [comment]
Pffft, just make a directory, cd into it and run `npx boringbits@latest yo`

**Comment by ryanstevens** [comment]
@josheverett actually, on 2nd thought don't worry about that last command.  Do what you requested in the issue `npx create-boring-app my-app` where my-app is either an existing directory, OR the cli tool will create that directory if it doesn't exist.
