### ISSUE TITLE
I created an app with create-boring-app but not sure what to do next.

### ISSUE THREAD

**Issue by josheverett** [ryanstevens/boringbits#19]
1. Used `npx create-boring-app my-app`.
2. Followed the prompts, including at the end to start the app.
3. Lots of output ending with "Compiled successfully."

Unsure what to do next.

A little bird told me to go to "https://boringlocal.com" in my browser, but nothing happens.

**Comment by ryanstevens** [comment]
I like the idea of just "opening" a browser to the right URL.  As far as the output probs won't be able to really change that as we pipe webpacks output to stdout.  

ALSO, gonna check to see if your running HAProxy and if not I'll launch it for you.
